#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Mar 23 12:12:55 2017

@author: brendontucker

need to generate a random number between 2 and 98, both inclusive
"""

import random


def genEven():
    ans = random.randint(0, 49)
    return ans * 2
    
