#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Mar 23 13:11:43 2017

@author: brendontucker

Stochastically generates and returns a uniformly distributed even number between 9 and 21
"""

import random


def stochasticNumber():
    ans = random.randint(11, 21)
    if ans % 2 == 0:
        return ans
    else:
        return ans - 1