#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Mar 25 10:27:04 2017

@author: brendontucker
"""

class IntSet(object):
    def __init__(self): 
        """Create an empty set of integers""" 
        self.vals = []
    
    def insert(self, e): 
        """Assumes e is an integer"""
        if not e in self.vals:
            self.vals.append(e)
            
    def member(self, e): 
        return e in self.vals
        
    
    def remove(self, e):
        try: 
            self.vals.remove(e)
        except:
            raise ValueError(str(e) + ' not found')
    

    def getMembers(self):
        return self.vals[:]
        
    def __str__(self):
        """Returns a string representation of self""" 
        self.vals.sort()
        result = ''
        for e in self.vals:
            result = result + str(e) + ','
        return '{' + result[:-1] + '}' #-1 omits trailing comma
        
        
        
s = IntSet()   
s.insert(3)
s.insert(4)         