#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Mar 21 16:03:35 2017

@author: brendontucker
"""

limit= 100
cows = {'Boo': 20, 'Horns': 25, 'MooMoo': 50, 'Lotus': 40, 'Miss Bella': 25, 'Milkshake': 40}

def comboGenerator():
    import itertools 
    
    cows_sorted = sorted(cows.items(), key=lambda x: x[1], reverse = True)

    comboList = list()
    for r in range(len(cows_sorted)):
        list1 = list(itertools.combinations(cows_sorted, r))
        comboList.append(list1)
        
    return cows_sorted