#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Mar 19 09:06:41 2017

@author: brendontucker

Think I took the wrong path on this one...
This type of solution should be correct most of the time but I think there are 
situations where it won't be. 
"""

import itertools 
from itertools import combinations

cows = {'Boo': 20, 'Horns': 25, 'MooMoo': 50, 'Lotus': 40, 'Miss Bella': 25, 'Milkshake': 40}

cows_sorted = sorted(cows.items(), key=lambda x: x[1], reverse = True)

comboList = list()
for r in range(len(cows_sorted)):
    list1 = list(itertools.combinations(cows_sorted, r))
    comboList.append(list1)    
    
