#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Mar 14 09:27:41 2017

@author: brendontucker

experimenting with a checkWeight function

 currentWeight = sum(tripWeights[position])    
    checkWeight = limit - currentWeight

want to turn this block of code into a helper function, needs to take 
a list with int as in input 
"""
cows = {'MooMoo': 85, 'Muscles': 65, 'Polaris': 20, 'Clover': 5, 'Lotus': 10, 'Louis': 45,
 'Horns': 50, 'Milkshake': 75, 'Patches': 60, 'Miss Bella': 15}

limit = 20

cows_sorted = sorted(cows.items(), key=lambda x: x[1], reverse = True)
tripWeights = [[1, 3, 5, 7, 11], [0, 8, 12], [12]]
currentWeight = 0    
checkWeight = 0       
position = 0

currentWeight = sum(tripWeights[position])    
checkWeight = limit - currentWeight

def weightChecker(tripWeights, limit, position):
    currentWeight = sum(tripWeights[position])    
    checkWeight = limit - currentWeight

    return checkWeight

weightChecker(tripWeights = tripWeights, limit = 10, position = 1 )
    
    