#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Mar 14 12:09:28 2017

@author: brendontucker
"""

cows = {'Daisy': 50, 'Lilly': 24, 'Buttercup': 72, 'Patches': 12, 'Rose': 50,
        'Willow': 35, 'Coco': 10, 'Abby': 38, 'Dottie': 85, 'Betsy': 65}

limit = 100

cows_sorted = sorted(cows.items(), key=lambda x: x[1], reverse = True)

#max number of trips can't be greater than the number of cows
cowList = [[] for x in range(len(cows_sorted))]
tripWeights = [[] for x in range(len(cows_sorted))]
cowNames = [[] for x in range(len(cows_sorted))]        
cowWeights = [[] for x in range(len(cows_sorted))]      
position = 0



counter = 0           
while counter < len(cows_sorted):
    cowNames[counter].append(cows_sorted[counter][0])
    counter += 1
counter = 0           
while counter < len(cows_sorted):
    cowWeights[counter].append(cows_sorted[counter][1])
    counter += 1



#fuck it, I'm going to just use a while loop

counter = 0 
counter2 = 0
while counter2 < len(cowList):
    counter = 0
    while counter < len(cowWeights):
        currentWeight = sum(tripWeights[position]) #+ cowWeights[counter][0] #this is now more like proposed weight    
        checkWeight = limit - currentWeight
        if checkWeight <= 0:
            counter += 1
            continue#not position, but do need a change here
        if cowWeights[counter][0] <= checkWeight:
            tripWeights[position].append(cowWeights[counter][0])
            cowWeights.pop([counter][0])
            cowList[position].append(cowNames[counter][0])
            cowNames.pop([counter][0])
            #counter += 1 #need to account for when the list is popped to len 1
        else:
            counter += 1
    position += 1
    counter2 += 1
    
counter = 0 
while counter < len(cowList):
    if cowList[counter] == []:
        cowList.pop(counter)
    else:
        counter +=1        
    






















    
'''    
for i in range(len(cowWeights)):
    currentWeight = sum(tripWeights[position])    
    checkWeight = limit - currentWeight
    if checkWeight <= 0:
        position += 1 #think I need a break here?
    if cowWeights[i][0] <= checkWeight:
        tripWeights[position].append(cowWeights[i][0])
        cowList[position].append(cowNames[i][0])
'''        
        
#test here to see if continue works like I htink it will
'''
for i in range(len(cowWeights)):
    currentWeight = sum(tripWeights[position])    
    checkWeight = limit - currentWeight
    if cowList[position] == []:
        pass
    else: 
    if checkWeight <= 0:
        position += 1#think I need a break here?
    if cowWeights[i][0] <= checkWeight:
        tripWeights[position].append(cowWeights[i][0])
        cowList[position].append(cowNames[i][0])
        
'''